name: VoteRanks
main: VoteRanks\VoteRanks
version: 1.0
api: [1.12.0]

load: POSTWORLD
author: [ecoron, LittleRon]
description: rankup a player as vote reward, or after time playing on server
website: https://github.com/ecoron/VoteRanks
commands:
    voteranks:
        description: rankup a player as vote reward
        usage: "/vr"
        aliases: [vr, voteranks, vote]
        permission: voteranks.command
    timeranks:
        description: check time to play for next rank
        usage: "/tr"
        aliases: [tr, timeranks]
        permission: timeranks.command
permissions:
    voteranks.command:
        description: "rankup a player as vote reward"
        default: true
    timeranks.command:
        description: "check time to play for next rank"
        default: true