# API key; Can be found on your server settings page (minecraftpocket-servers.com)
APIKey: ""

# URL where players can vote for this server;
VoteURL: ""

# list of ranks that can be reached. cutomize this with your server ranks
# ranks must have the same name like the group in pureperms
# add all groups that exists, and add the order by giving them a value from 1 to X
# where 1 is the lowest rank and X the highest
Ranks:
    Guest: 1
    rank2: 2
    rank3: 3
    rank4: 4
    rank5: 5
    job1: 6
    job2: 7
    job3: 8
    Admin: 20
    Owner: 50
    OP: 100

JobRanks:
    job1: 5
    job2: 5
    job3: 5

# the fallbackrank if a player stop the job, for cases where players
# reached a rank by voting but dint reached the required time in autoranks
JobStopFallback:
    id: 5
    title: "rank5"

VoteRanks:
    Guest: 1
    rank2: 2
    rank3: 3

# time to reach this rank, ranks must have the same name like in pureperms
AutoRanks:
    Guest: true
    rank1: 20
    rank2: 60
    rank3: 120
    rank4: 240
    rank5: 720

##messages
Messages:
    command-in-game: "Comando debe utilizarse en el juego."
    error-fetching-vote: "[RankUp] Error al obtener el estado de voto! Inténtalo luego."
    no-permission: "No tienes permiso para votar."
    pureperms-loaded: "PurePerms cargado con éxito"
    pureperms-notfound: "No se encontraron las dependencias de PurePerms"
    rank-new: "Ahora eres rango ##rank##"
    rank-failed: "RankUp falló con el rango: ##rank##"
    vote-nextday: "Ya has votado hoy! Vuelve mañana a votar de nuevo."
    vote-success: "##player## votó con /vote y tiene un rango más alto!"
    vote-open: "Usted no ha votado todavía!\n +++ ##voteurl## +++ \nVotar para obtener un rango más alto!"
    timer-usage: "Usa /tr check ##player##"
    timer-neverplayed: "El jugador ##player## nunca jugó en este servidor"
    timer-newplayer: "##player## ha jugado menos de 1 minuto en este servidor"
    timer-newrank: "##player## ha alcanzado un nuevo rango: ##rank##"
    timer-rankis: "Rango es: ##rank##"
    timer-timeplayed: "Tu has jugado ##timeplayed## minutos en este servidor.\n ##timetoplay## minutos para el siguiente rango"
    timer-timeplayer: "Has jugado ##timeplayed## minutos en éste servidor"
    job-list: "Puedes elegir uno de esos puestos de trabajo: ##joblist##"
    job-choose: "Por favor seleccione uno de los puestos de trabajo:: ##joblist##"
    job-rank-low: "No puedes elegir este trabajo, tu rango es demasiado bajo"
    job-rank-error: "Vaya que hay un error, inténtelo de nuevo más tarde"
    job-usage: "Puestos de trabajo: /job list\Escoge un trabajo: /job start <Nombre del trabajo>"
    job-no-stop: "No tienes un trabajo para detener, utiliza /job start <Nombre del trabajo> para iniciar un trabajo"
